name: Comprueba YAML
on:
  push:
    paths:
      - "iv.yaml"
jobs:
  CompruevaIVyaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comprueba yaml
        run: yq eval iv.yaml || echo "::error file=iv.yaml,line=1::Error de sintaxis" && exit 1
